In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("height-weight.csv")

In [4]:
data

    Weight  Height
0       45     120
1       58     135
2       48     123
3       60     145
4       70     160
5       78     162
6       80     163
7       90     175
8       95     182
9       78     170
10      82     176
11      95     182
12     105     175
13     100     183
14      85     170
15      78     177
16      50     140
17      65     159
18      76     150
19      87     167
20      45     129
21      56     140
22      72     160

Process of builiding ML Project

Data collection

Data understanding

Data cleaning 

Feature engineering

Model Building
* Variable declaration
* split the data
* call the model
* train the model
* evaluation
  
Model deployment

In [9]:
# Variable Declaration

x = data[["Height"]]  # input variable  # Always a data frame # 2 dimensional 
y = data["Weight"]  # output variable

In [10]:
y

0      45
1      58
2      48
3      60
4      70
5      78
6      80
7      90
8      95
9      78
10     82
11     95
12    105
13    100
14     85
15     78
16     50
17     65
18     76
19     87
20     45
21     56
22     72
Name: Weight, dtype: int64

In [14]:
# Split the data into train and test

In [12]:
# scikit learn: a library to build the ml model
!pip install scikit-learn

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\shriy\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn) (2.4.1)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 5.4 MB/s eta 0:00:02
   ----- ---------------------------------- 1.0/8.1 MB 3.7 MB/s eta 0:00:02
   ------ --------------------------------- 1.3/8.1 MB 2.9 MB/s eta 0:00:03
   ------ --------------------------------- 1.3/8.1 MB 2.9 MB/s eta 0:00:03
   ------- -------------------------------- 1.6/8.1 MB 1.7 MB/s eta 0:00:04
   ----------- ---------------------------- 2.4/8.1 MB 1.9 MB/s eta 0:00:04
   -------------- ------------------------- 2.9/8.1 MB 2.0 MB/s eta 0:00:03
   --------------- ------------------------ 3.1/8.1 MB 1.9 MB/s eta 0:00:03
   ------------------ --------------------- 3.7/8.1 MB 2.0 MB/s eta 0:00:03
   -------------------- ------------------- 4.2/8.1 MB 2.1 MB/s eta 0:00:02
   ---------------------- ----------------- 4.5/8.1 MB 2.0 MB/s eta 0:00:02
   ---------------------- ----------------- 4.5/8.1 MB 2.0 MB/s eta 0:00:02
   ----------------------- ---------------- 4.7/8.1 MB 1.8 MB/s eta 0:00:02
   ----------------------- ---------------- 4.7/8.1 MB 1.8 MB/s eta 0:00:02
   ----------------------- ---------------- 4.7/8.1 MB 1.8 MB/s eta 0:00:02
   ------------------------ --------------- 5.0/8.1 MB 1.6 MB/s eta 0:00:03
   ------------------------- -------------- 5.2/8.1 MB 1.5 MB/s eta 0:00:02
   ------------------------- -------------- 5.2/8.1 MB 1.5 MB/s eta 0:00:02
   ------------------------- -------------- 5.2/8.1 MB 1.5 MB/s eta 0:00:02
   --------------------------- ------------ 5.5/8.1 MB 1.4 MB/s eta 0:00:02
   --------------------------- ------------ 5.5/8.1 MB 1.4 MB/s eta 0:00:02
   --------------------------- ------------ 5.5/8.1 MB 1.4 MB/s eta 0:00:02
   ---------------------------- ----------- 5.8/8.1 MB 1.2 MB/s eta 0:00:02
   ----------------------------- ---------- 6.0/8.1 MB 1.2 MB/s eta 0:00:02
   ----------------------------- ---------- 6.0/8.1 MB 1.2 MB/s eta 0:00:02
   ----------------------------- ---------- 6.0/8.1 MB 1.2 MB/s eta 0:00:02
   ------------------------------- -------- 6.3/8.1 MB 1.1 MB/s eta 0:00:02
   ------------------------------- -------- 6.3/8.1 MB 1.1 MB/s eta 0:00:02
   ------------------------------- -------- 6.3/8.1 MB 1.1 MB/s eta 0:00:02
   ------------------------------- -------- 6.3/8.1 MB 1.1 MB/s eta 0:00:02
   -------------------------------- ------- 6.6/8.1 MB 1.0 MB/s eta 0:00:02
   -------------------------------- ------- 6.6/8.1 MB 1.0 MB/s eta 0:00:02
   -------------------------------- ------- 6.6/8.1 MB 1.0 MB/s eta 0:00:02
   --------------------------------- ------ 6.8/8.1 MB 969.4 kB/s eta 0:00:02
   --------------------------------- ------ 6.8/8.1 MB 969.4 kB/s eta 0:00:02
   --------------------------------- ------ 6.8/8.1 MB 969.4 kB/s eta 0:00:02
   --------------------------------- ------ 6.8/8.1 MB 969.4 kB/s eta 0:00:02
   ---------------------------------- ----- 7.1/8.1 MB 899.5 kB/s eta 0:00:02
   ------------------------------------ --- 7.3/8.1 MB 896.6 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 933.4 kB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 954.5 kB/s  0:00:08
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl (37.3 MB)
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.3 MB ? eta -:--:--
    --------------------------------------- 0.5/37.3 MB 3.3 MB/s eta 0:00:12
    --------------------------------------- 0.8/37.3 MB 2.2 MB/s eta 0:00:17
    --------------------------------------- 0.8/37.3 MB 2.2 MB/s eta 0:00:17
   - -------------------------------------- 1.0/37.3 MB 980.4 kB/s eta 0:00:37
   - -------------------------------------- 1.0/37.3 MB 980.4 kB/s eta 0:00:37
   - -------------------------------------- 1.6/37.3 MB 1.1 MB/s eta 0:00:34
   - -------------------------------------- 1.8/37.3 MB 1.1 MB/s eta 0:00:32
   - -------------------------------------- 1.8/37.3 MB 1.1 MB/s eta 0:00:32
   -- ------------------------------------- 2.1/37.3 MB 1.1 MB/s eta 0:00:34
   -- ------------------------------------- 2.4/37.3 MB 1.1 MB/s eta 0:00:33
   -- ------------------------------------- 2.4/37.3 MB 1.1 MB/s eta 0:00:33
   -- ------------------------------------- 2.6/37.3 MB 972.1 kB/s eta 0:00:36
   -- ------------------------------------- 2.6/37.3 MB 972.1 kB/s eta 0:00:36
   --- ------------------------------------ 3.4/37.3 MB 1.1 MB/s eta 0:00:31
   ---- ----------------------------------- 4.2/37.3 MB 1.3 MB/s eta 0:00:26
   ---- ----------------------------------- 4.5/37.3 MB 1.3 MB/s eta 0:00:26
   ----- ---------------------------------- 4.7/37.3 MB 1.3 MB/s eta 0:00:26
   ----- ---------------------------------- 5.2/37.3 MB 1.4 MB/s eta 0:00:24
   ------ --------------------------------- 6.3/37.3 MB 1.6 MB/s eta 0:00:20
   -------- ------------------------------- 7.6/37.3 MB 1.8 MB/s eta 0:00:17
   -------- ------------------------------- 8.1/37.3 MB 1.8 MB/s eta 0:00:17
   -------- ------------------------------- 8.4/37.3 MB 1.8 MB/s eta 0:00:17
   ---------- ----------------------------- 9.4/37.3 MB 1.9 MB/s eta 0:00:15
   ----------- ---------------------------- 10.5/37.3 MB 2.1 MB/s eta 0:00:13
   ------------ --------------------------- 11.8/37.3 MB 2.2 MB/s eta 0:00:12
   -------------- ------------------------- 13.6/37.3 MB 2.5 MB/s eta 0:00:10
   ---------------- ----------------------- 14.9/37.3 MB 2.6 MB/s eta 0:00:09
   ----------------- ---------------------- 16.5/37.3 MB 2.8 MB/s eta 0:00:08
   -------------------- ------------------- 18.9/37.3 MB 3.1 MB/s eta 0:00:06
   ---------------------- ----------------- 21.0/37.3 MB 3.3 MB/s eta 0:00:05
   ------------------------- -------------- 23.3/37.3 MB 3.6 MB/s eta 0:00:04
   -------------------------- ------------- 24.6/37.3 MB 3.7 MB/s eta 0:00:04
   --------------------------- ------------ 25.4/37.3 MB 3.7 MB/s eta 0:00:04
   ---------------------------- ----------- 26.2/37.3 MB 3.7 MB/s eta 0:00:03
   ----------------------------- ---------- 27.3/37.3 MB 3.7 MB/s eta 0:00:03
   ------------------------------ --------- 28.6/37.3 MB 3.8 MB/s eta 0:00:03
   -------------------------------- ------- 30.1/37.3 MB 3.9 MB/s eta 0:00:02
   ---------------------------------- ----- 32.2/37.3 MB 4.1 MB/s eta 0:00:02
   ----------------------------------- ---- 33.3/37.3 MB 4.1 MB/s eta 0:00:01
   ------------------------------------ --- 33.8/37.3 MB 4.1 MB/s eta 0:00:01
   ------------------------------------ --- 33.8/37.3 MB 4.1 MB/s eta 0:00:01
   ---------------------------------------  37.2/37.3 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------- 37.3/37.3 MB 4.2 MB/s  0:00:09
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ---------------------------------------- 4/4 [scikit-learn]

Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 threadpoolctl-3.6.0

In [16]:
from sklearn.model_selection import train_test_split   
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.30, random_state = 5)

In [17]:
x_train.shape

(16, 1)

In [18]:
x_test.shape

(7, 1)

In [19]:
y_train.shape

(16,)

In [20]:
y_test.shape

(7,)

In [ ]:
# Calling the model _ regression model

In [21]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [22]:
model

LinearRegression()

In [23]:
# train the model

In [24]:
model.fit(x_train, y_train)

LinearRegression()

In [25]:
model.coef_

array([0.84830164])

In [26]:
model.intercept_

np.float64(-61.051989108362534)

In [28]:
y_pred = model.predict(x_test)

In [29]:
from sklearn.metrics import r2_score

In [30]:
print("Accracy is : ", np.round(r2_score(y_pred, y_test)*100,2) , "%")

Accracy is :  84.91 %

In [31]:
r2_score(y_pred, y_test)

0.8491307842639152

In [33]:
markds = pd.read_csv("Marksheet.csv")

In [34]:
markds

    Student_Name  Hindi  English  Maths  Science  SST  Total  Percentage
0    Arjun Singh     45     49.0     86       63   70  283.0        56.6
1    Mohit Yadav     46     53.0     78       64   68  290.0        58.0
2    Amit tiwari     47     48.0     67       67   56  263.0        52.6
3     Sumit Negi     48     49.0     89       62   67  276.0        55.2
4      Rohit Raj     49     48.5     95       45   78  274.5        54.9
5   Shivani Negi     50     48.0     97       78   89  320.0        64.0
6          Jyoti     51     47.5     72       87   90  333.5        66.7
7          Arpit     52     47.0     95       65   76  297.0        59.4
8   Surjan Singh     53     46.5     80       65   78  309.5        61.9
9      Duryodhan     54     46.0     91       45   65  288.0        57.6
10         Bheem     55     45.5     82       59   45  283.5        56.7
11         Nakul     56     45.0     60       76   76  313.0        62.6
12        Sahdev     57     44.5     80       56   87  324.5        64.9
13       Krishna     58     44.0     90       56   68  316.0        63.2
14      Bheeshma     56     87.0     57       87   44  331.0        66.2
15         Kunti     66     78.0     54       76   55  329.0        65.8
16  Dhritrashtra     77     76.0     77       67   66  363.0        72.6
17      Shantanu     88     67.0     66       65   77  363.0        72.6
18        Bharat     57     66.0     55       69   67  314.0        62.8

In [46]:
x = pd.DataFrame(markds.iloc[:, 3])
y = pd.DataFrame(markds.iloc[:, -1])

In [47]:
x

    Maths
0      86
1      78
2      67
3      89
4      95
5      97
6      72
7      95
8      80
9      91
10     82
11     60
12     80
13     90
14     57
15     54
16     77
17     66
18     55

In [48]:
y

    Percentage
0         56.6
1         58.0
2         52.6
3         55.2
4         54.9
5         64.0
6         66.7
7         59.4
8         61.9
9         57.6
10        56.7
11        62.6
12        64.9
13        63.2
14        66.2
15        65.8
16        72.6
17        72.6
18        62.8

In [49]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.30, random_state = 5)

In [50]:
model_2 = LinearRegression()

In [51]:
model_2

LinearRegression()

In [52]:
model_2.fit(x_train, y_train)

LinearRegression()

In [53]:
model_2.coef_

array([[-0.24421272]])

In [54]:
model_2.intercept_

array([81.64786236])

In [55]:
y_pred = model_2.predict(x_test)

In [56]:
print("Accracy is : ", np.round(r2_score(y_pred, y_test)*100,2) , "%")

Accracy is :  -449.65 %